---
# Debian-specific tasks for uninstalling TSM


- name: debian | get the filenames for all of the DEB packages
  ansible.builtin.find:
    paths: "/usr/local/src/tivoli"
    patterns: "*.deb"
    file_type: file
  register: _tsmbackup_deb_filenames
  become: yes
  tags:
    - tsm_upgrade

- name: debian | uninstall the DEB packages
  ansible.builtin.apt:
    name: "{{ item.path|replace('/usr/local/src/tivoli', '')|replace('.amd64.deb', '') }}"
    state: absent
  loop: "{{ _tsmbackup_deb_filenames.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path|replace('/usr/local/src/tivoli', '')|replace('.amd64.deb', '') }}"
  when: "'api64' in item.path or 'ba.' in item.path"
  become: yes
  tags:
    - tsm_upgrade

- name: debian | uninstall the supporting DEB packages
  ansible.builtin.apt:
    name: "{{ item.path|replace('/usr/local/src/tivoli', '')|split('_').0 }}"
    state: absent
  loop: "{{ _tsmbackup_deb_filenames.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path|replace('/usr/local/src/tivoli', '')|split('_').0 }}"
  when: "'gsk' in item.path"
  become: yes
  tags:
    - tsm_upgrade

