---
# Debian-specific tasks for uninstalling TSM


- name: debian | get the filenames for all of the DEB packages
  ansible.builtin.find:
    paths: /usr/local/src/tivoli
    patterns: "*.deb"
    file_type: file
  register: _tsmbackup_deb_filenames
  become: yes
  tags:
    - tsm_upgrade

- name: debian | uninstall the DEB packages
  ansible.builtin.apt:
    deb: "{{ item.path }}"
    state: absent
  loop: "{{ _tsmbackup_deb_filenames.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path }}"
  when: "'gsk' in item.path or 'api64' in item.path or 'ba.' in item.path"
  become: yes
  tags:
    - tsm_upgrade

