---
# Install and configure the IBM Spectrum Protect (TSM) backup client


- name: include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - tsm_install
    - tsm_upgrade


##
# Remove existing install
##

- name: check for existing download
  ansible.builtin.stat:
    path: "/usr/local/src/tivoli"
  register: _tsmbackup_existing_download
  become: yes
  tags:
    - tsm_upgrade

# - name: uninstall TSM
#   include_tasks: "{{ ansible_os_family }}_uninstall.yml"
#   tags:
#     - tsm_upgrade

- name: remove existing download
  ansible.builtin.file:
    path: "/usr/local/src/tivoli"
    state: absent
  become: yes
  when: _tsmbackup_existing_download.stat.isdir is defined and _tsmbackup_existing_download.stat.isdir
  tags:
    - tsm_upgrade

- name: check for existing installation
  ansible.builtin.stat:
    path: "/opt/tivoli"
  register: _tsmbackup_existing_install
  become: yes
  tags:
    - tsm_upgrade

- name: remove existing installation
  ansible.builtin.file:
    path: "/opt/tivoli"
    state: absent
  become: yes
  when: _tsmbackup_existing_install.stat.isdir is defined and _tsmbackup_existing_install.stat.isdir
  tags:
    - tsm_upgrade



##
# Install the TSM backup client
##

- name: create the src directory
  ansible.builtin.file:
    path: "/usr/local/src"
    owner: root
    group: adm
    mode: 0775
    state: directory
  become: yes
  tags:
    - tsm_install
    - tsm_upgrade

- name: create the tivoli directory
  ansible.builtin.file:
    path: "/usr/local/src/tivoli"
    owner: root
    group: adm
    mode: 0775
    state: directory
  become: yes
  tags:
    - tsm_install
    - tsm_upgrade

- name: extract the tarball
  ansible.builtin.unarchive:
    src: "{{ tsmbackup_client_url }}"
    dest: "/usr/local/src/tivoli"
    remote_src: yes
    creates: "/usr/local/src/tivoli/README.htm"
    owner: root
    group: adm
  become: yes
  tags:
    - tsm_install
    - tsm_upgrade

- name: install TSM
  include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - tsm_install
    - tsm_upgrade



##
# Configure the TSM backup client
##

- name: check if TSM installed
  ansible.builtin.stat:
    path: /opt/tivoli/tsm/client/ba/bin
  register: _tsmbackup_tsm_exists
  become: yes
  tags:
    - tsm_config
    - tsm_cron
    - tsm_install
    - tsm_upgrade
    - cron

- block:
  - name: TSM system configuration
    template:
      src: dsm.sys.j2
      dest: /opt/tivoli/tsm/client/ba/bin/dsm.sys
      owner: "{{ devops_user|default(ansible_ssh_user) }}"
      group: adm
      mode: 0660

  - name: TSM client configuration
    template:
      src: dsm.opt.j2
      dest: /opt/tivoli/tsm/client/ba/bin/dsm.opt
      owner: "{{ devops_user|default(ansible_ssh_user) }}"
      group: adm
      mode: 0660

  - name: TSM include/exclude file list
    template:
      src: tsm.exclude.j2
      dest: /opt/tivoli/tsm/client/ba/bin/tsm.exclude.list
      owner: "{{ devops_user|default(ansible_ssh_user) }}"
      group: adm
      mode: 0660
  when: _tsmbackup_tsm_exists.stat.isdir is defined and _tsmbackup_tsm_exists.stat.isdir
  become: yes
  tags:
    - tsm_config
    - tsm_install
    - tsm_upgrade


- name: "Install SSL CA certificate"
  block:
    - name: Fetch the SSL CA certificate
      ansible.builtin.get_url:
        url: "{{ tsmbackup_ssl_url }}"
        dest: "/opt/tivoli/tsm/client/ba/bin/{{ tsmbackup_ssl_file }}"
        owner: root
        group: root
        mode: 0400
    - name: Install the SSL CA certificate
      ansible.builtin.command:
        argv:
          - dsmcert
          - "-add"
          - "-server"
          - "{{ tsmbackup_ssl_server }}"
          - "-file"
          - "/opt/tivoli/tsm/client/ba/bin/{{ tsmbackup_ssl_file }}"
  when: "tsmbackup_ssl_url != ''"
  become: yes
  tags:
    - tsm_install
    - tsm_upgrade


##
# Schedule the TSM backups
##
- name: schedule backups
  template:
    src: tsm.cron.j2
    dest: /etc/cron.d/tsm-backups
    owner: root
    group: root
    mode: 0644
  become: yes
  when: _tsmbackup_tsm_exists.stat.isdir is defined and _tsmbackup_tsm_exists.stat.isdir
  tags:
    - tsm_config
    - tsm_cron
    - tsm_install
    - cron

